### ISSUE TITLE
TestSpecTests_invalid fails

### ISSUE THREAD

**Issue by bdrung** [komkom/toml#7]
`TestSpecTests_invalid` fails on Debian unstable (on every architecture):
```
=== RUN   TestSpecTests_invalid
--- FAIL: TestSpecTests_invalid (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1fd30c]

goroutine 24 [running]:
testing.tRunner.func1.2({0x22ae00, 0x3bcde0})
	/usr/lib/go-1.18/src/testing/testing.go:1389 +0x27c
testing.tRunner.func1()
	/usr/lib/go-1.18/src/testing/testing.go:1392 +0x3f4
panic({0x22ae00, 0x3bcde0})
	/usr/lib/go-1.18/src/runtime/panic.go:838 +0x23c
github.com/komkom/toml.TestSpecTests_invalid.func1({0x250adb, 0x18}, {0x0, 0x0}, {0x29aed0, 0x14f1698})
	_build/src/github.com/komkom/toml/reader_test.go:300 +0x38
path/filepath.Walk({0x250adb, 0x18}, 0x142f788)
	/usr/lib/go-1.18/src/path/filepath/path.go:515 +0x6c
github.com/komkom/toml.TestSpecTests_invalid(0x1482b40)
	_build/src/github.com/komkom/toml/reader_test.go:297 +0x74
testing.tRunner(0x1482b40, 0x25fb8c)
	/usr/lib/go-1.18/src/testing/testing.go:1439 +0x118
created by testing.(*T).Run
	/usr/lib/go-1.18/src/testing/testing.go:1486 +0x3a0
```

**Comment by komkom** [comment]
Is it possible to reproduce this error on none debain machines? Could you run the test with `go test -v -run TestSpecTests_invalid` to get more logs?

**Comment by bdrung** [comment]
Steps to reproduce: Import the code from the toml master branch into the `golang-github-komkom-toml` Debian package or copy the `debian` directory from  `golang-github-komkom-toml` to the toml master branch. Then you can generate a source package and build it with sbuild.

Test result:
* Debian unstable: `TestSpecTests_invalid` fails
* Ubuntu 22.10 (kinetic): `TestSpecTests_invalid` fails

Ubuntu 22.10 (kinetic) log:
```
=== RUN   TestSpecTests_invalid
--- FAIL: TestSpecTests_invalid (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5ce125]

goroutine 9 [running]:
testing.tRunner.func1.2({0x5f27a0, 0x770e10})
	/usr/lib/go-1.18/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/lib/go-1.18/src/testing/testing.go:1392 +0x39f
panic({0x5f27a0, 0x770e10})
	/usr/lib/go-1.18/src/runtime/panic.go:838 +0x207
github.com/komkom/toml.TestSpecTests_invalid.func1({0x629c06, 0x18}, {0x0, 0x0}, {0x514?, 0x4d9bc0?})
	/<<PKGBUILDDIR>>/_build/src/github.com/komkom/toml/reader_test.go:300 +0x65
path/filepath.Walk({0x629c06, 0x18}, 0xc000064740)
	/usr/lib/go-1.18/src/path/filepath/path.go:515 +0x50
github.com/komkom/toml.TestSpecTests_invalid(0xc0000af860)
	/<<PKGBUILDDIR>>/_build/src/github.com/komkom/toml/reader_test.go:297 +0x79
testing.tRunner(0xc0000af860, 0x639318)
	/usr/lib/go-1.18/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/usr/lib/go-1.18/src/testing/testing.go:1486 +0x35f
```

`dh_auto_test` calls:
```
cd _build && go test -vet=off -v -p 16 github.com/komkom/toml github.com/komkom/toml/internal
```
So the test is already run in verbose mode and that stack trace it the result.
